name: total_load_up
description: This application helps all total clients to easily acccess fuel
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.7.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    font_awesome_flutter:
    flutter_icons:
    flutter_staggered_grid_view:
    bubble_tab_indicator:
    cloud_firestore: ^3.1.5
    firebase_auth: ^3.3.4
    firebase_core: ^1.10.6
    toast:
    mailer:
    barcode_widget:
    flutter_barcode_scanner: ^2.0.0
    cupertino_icons: ^0.1.3
    provider:
    permission_handler:
    passcode_screen: ^1.0.2
    qr_code_scanner:
    firebase_options:
    google_maps_flutter: ^2.1.1
    permission:
    image_picker: ^0.8.2
    geolocator: 
    http:
    twilio_flutter:
    charts_flutter:
    local_auth: ^1.1.9
    firebase_database: ^9.0.4
    transparent_image:
    cached_network_image:
    flutter_spinkit:
    firebase_storage:
dev_dependencies:
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true
    assets:
        - assets/images/
    # fonts:
    #     - family: Montserrat
    #       fonts:
    #         - asset: assets/fonts/Montserrat/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    # fonts:
    #     - family: Montserrat
    #       fonts:
    #         - asset: assets/fonts/Montserrat/
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages